services:
  postgres:
    image: postgres:latest
    environment:
        POSTGRES_USER: ${SPRING_PRODUCT_USER}
        POSTGRES_PASSWORD: ${SPRING_PRODUCT_PASSWORD}
        POSTGRES_DB: ${SPRING_PRODUCT_DB}
    ports:
      - "${DB_PORT}:5432"
    container_name: db-spring-product
    volumes:
      - db-spring-product-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-spring-product
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-spring-product-data:/data

volumes:
  db-spring-product-data:
  redis-spring-product-data: